import Link from "next/link"
import { ChefHat, ArrowLeft } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-rose-100 via-amber-50 to-indigo-200 dark:from-slate-950 dark:via-slate-900 dark:to-indigo-950">
      <div className="container mx-auto max-w-4xl px-4 py-8">
        <Link href="/">
          <Button variant="ghost" className="mb-6 text-foreground hover:bg-black/5 dark:hover:bg-white/10">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Home
          </Button>
        </Link>

        <Card className="glass-panel">
          <CardHeader className="text-center border-b border-black/10 dark:border-white/20">
            <div className="flex justify-center mb-4">
              <div className="bg-gradient-to-r from-pink-500 to-purple-500 p-3 rounded-xl">
                <ChefHat className="w-8 h-8 text-white" />
              </div>
            </div>
            <CardTitle className="text-3xl text-foreground">Terms of Service</CardTitle>
            <p className="text-foreground/70">Last updated: December 3, 2025</p>
          </CardHeader>
          <CardContent className="prose prose-slate dark:prose-invert max-w-none p-8">
            <div className="space-y-8 text-foreground/90">
              <section>
                <h2 className="text-xl font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
                <p className="leading-relaxed">
                  By accessing and using Chefy.Y ("the Service"), you agree to be bound by these Terms of Service. If
                  you do not agree to these terms, please do not use the Service.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-3">2. Description of Service</h2>
                <p className="leading-relaxed">
                  Chefy.Y is an AI-powered recipe generation service that creates recipes based on user-provided
                  ingredients, cooking methods, and preferences. The Service uses artificial intelligence to suggest
                  recipes and provide cooking assistance.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-3">3. User Responsibilities</h2>
                <ul className="list-disc list-inside space-y-2">
                  <li>You are responsible for verifying all recipe information before cooking</li>
                  <li>Check for food allergies and dietary restrictions independently</li>
                  <li>Follow proper food safety guidelines when preparing meals</li>
                  <li>Use the Service for lawful purposes only</li>
                </ul>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-3">4. AI-Generated Content Disclaimer</h2>
                <p className="leading-relaxed">
                  Recipes and cooking advice provided by Chefy.Y are generated by artificial intelligence. While we
                  strive for accuracy, AI-generated content may contain errors. Always use your judgment and consult
                  professional sources for dietary or health-related decisions.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-3">5. Intellectual Property</h2>
                <p className="leading-relaxed">
                  The Service, including its design, features, and content, is owned by Chefy.Y. Recipes you generate
                  are for your personal use. You may share recipes but not claim them as original works for commercial
                  purposes.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-3">6. Limitation of Liability</h2>
                <p className="leading-relaxed">
                  Chefy.Y is provided "as is" without warranties. We are not liable for any damages arising from your
                  use of the Service, including but not limited to foodborne illness, allergic reactions, or
                  unsatisfactory cooking results.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-3">7. Changes to Terms</h2>
                <p className="leading-relaxed">
                  We reserve the right to modify these terms at any time. Continued use of the Service after changes
                  constitutes acceptance of the new terms.
                </p>
              </section>

              <section>
                <h2 className="text-xl font-semibold text-foreground mb-3">8. Contact</h2>
                <p className="leading-relaxed">
                  For questions about these Terms, please contact us through our website.
                </p>
              </section>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

